### ISSUE TITLE
On K8 Cluster create Loadbalancer Service

### ISSUE THREAD

**Issue by x-snackage-x** [ZHAW-PM4-Compass/compass#24]

**Comment by brunndar** [comment]
Story Change:
Instead of Ingress we use simple Loadbalancer Service.
Why?
In many cases, especially for more complex applications with multiple services, Ingress is preferred because it offers more granular control over routing and enables easier management of external access. However, if you have a simple application that only requires exposing a single service, a LoadBalancer might be sufficient and simpler to set up.
